### ISSUE TITLE
Discussion about the GRIN optimizer

### ISSUE THREAD

**Issue by csabahruska** [Z-snails/Idris2-Grin#1]
Hi,

Would you like to have a video meeting and discuss the details of the GRIN optimizer?

Cheers,
Csaba Hruska

**Comment by Z-snails** [comment]
Would this be a discussion about using your implementation of GRIN, the roadmap for the GRIN project, or something else?

I've managed to get past the `SimpleDeadParameterElimination` not working properly by implementing it (I think) correctly in Idris, but now I've got another problem so help would be appreciated.

**Comment by csabahruska** [comment]
The topic can be anything that is relevant, i.e. using the current GRIN implementation and also project future plans.
My schedule is quite flexible. What time works for you?

**Comment by Z-snails** [comment]
I'll email you, is the email in your github bio good?

**Comment by csabahruska** [comment]
Ok.

**Comment by Z-snails** [comment]
Huge thanks to Csaba, the discussion was very helpful.
